apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-k8s
spec:
  selector:
    matchLabels:
      app: deletepg
  replicas: 1
  template:
    metadata:
      labels:
        app: deletepg
    spec:
      containers:
        - name: k8s-delete
          image: jav1prl/microservices:delete-service-image
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: my-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: delete-svc
spec:
  selector:
    app: deletepg
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8080
      name: http
  type: LoadBalancer
