version: '3.9'

services:
  create-service:
    container_name: create-service
    image: jav1prl/microservices:create-service-image
    build: ./create
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - microservices-net

  update-service:
    container_name: update-service
    image: jav1prl/microservices:update-service-image
    build: ./update
    ports:
      - "8082:8080"
    depends_on:
      - database
    networks:
      - microservices-net

  delete-service:
    container_name: delete-service
    image: jav1prl/microservices:delete-service-image
    build: ./delete
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - microservices-net

  list-service:
    container_name: list-service
    image: jav1prl/microservices:list-service-image
    build: ./list
    ports:
      - "8084:8080"
    depends_on:
      - database
    networks:
      - microservices-net

  database:
    container_name: java_db
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - microservices-net

networks:
  microservices-net:
